name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run Pylint
        run: |
          pylint --ignore-paths=bt_venv --fail-on=W,E,F --exit-zero ./

      - name: Run flake8
        run: |
          flake8 .

      - name: Run mypy
        run: |
          mypy .

      - name: Run Black
        run: |
          black --check .

      - name: Run unit tests
        run: pytest ./tests/
